apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "task-manager.fullname" . }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: true
  tags:
    - name: {{ .Values.image.tag }}
      from:
        kind: DockerImage
        name: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      importPolicy:
        scheduled: true
